version: "3.3"

services:
  ## backing services

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=lol123
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    # ports:
    #   - "3306:3306"

  ## application services

  ratelimits-service:
    image: ratelimits-service:latest
    ports:
      - 10000:80
    depends_on:
      - mysql
    volumes:
      - .:/srv/root
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
